### ISSUE TITLE
Can't call service thermiq_mqtt.write_reg

### ISSUE THREAD

**Issue by barvidss** [ThermIQ/thermiq_mqtt-ha#19]
## Version of the custom_component
v.1.2.3

## Configuration

```yaml

thermiq_mqtt:
  mqtt_node: ThermIQ/ThermIQ-mqtt-bb
  thermiq_dbg: False

```

## Describe the bug
When calling the service thermiq_mqtt.write_reg with the provided example values the value is'nt change on the pump and the Core log gives me an error.

How I call the service:
```yaml
service: thermiq_mqtt.write_reg
data:
  reg: r32
  value: 20
  bitmask: 2
```
## Debug log

```text

2021-12-27 01:14:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547156479376] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1532, in _execute_service
    handler.job.target(service_call)
  File "/config/custom_components/thermiq_mqtt/__init__.py", line 395, in write_reg_service
    reg = int(k[1:], 16)
ValueError: invalid literal for int() with base 16: 'ime'

```

**Comment by ThermIQ** [comment]
Resolved in v1.2.4
