### ISSUE TITLE
write_id no longer working

### ISSUE THREAD

**Issue by karlvans** [ThermIQ/thermiq_mqtt-ha#5]
## Configuration

```yaml

automations + configuration is added

```

## Describe the bug
No response from "Call service thermiq_mqtt.write_id"
I am unable to change any value of the heathpump (I was able to do this prior to the new version).

## Debug log

```text

2021-11-18 16:44:47 ERROR (MainThread) [homeassistant.components.automation.thermiq_input_number_to_mqtt] ThermIQ, Input number to MQTT: Error executing script. Unexpected error for call_service at pos 1: a coroutine was expected, got None
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1532, in _execute_service
handler.job.target(service_call)
File "/config/custom_components/thermiq_mqtt/__init__.py", line 186, in write_id_service
hass.async_create_task(hass.components.mqtt.async_publish(conf.cmd_topic, msg))
File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
task: asyncio.Task = self.loop.create_task(target)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-18 16:44:47 ERROR (MainThread) [homeassistant.components.automation.thermiq_input_number_to_mqtt] While executing automation automation.thermiq_input_number_to_mqtt
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 516, in async_trigger
await self.action_script.async_run(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1532, in _execute_service
handler.job.target(service_call)
File "/config/custom_components/thermiq_mqtt/__init__.py", line 186, in write_id_service
hass.async_create_task(hass.components.mqtt.async_publish(conf.cmd_topic, msg))
File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
task: asyncio.Task = self.loop.create_task(target)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
```

**Comment by ThermIQ** [comment]
Sorry for that. I've done a major rework of the internals. Please give the new release atry

**Comment by karlvans** [comment]
Hi, updated to the new release.
I am still not able to change variables.

When eg. changing the indoor target temperature (input_number.thermiq_rum_bor2) from 19 to 20°C it changes for a few seconds but then goes back to the initial 19°C 

I now also see lots of duplicate entities like:

- sensor.thermiq_t_ute --> no longer giving a value
- thermiq_mqtt.t_ute --> giving the value of heathpump, however without an icon or the correct unit (no °C anymore)

**Comment by karlvans** [comment]
Getting this error every 30 seconds:

```text

2021-11-19 17:05:48 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'ThermIQ/ThermIQ-mqtt/data': '{"Client_Name":"ThermIQ_2462ABE591F8","app_info":"ThermIQ-mqtt 2.12","reason":"T","r00":12,"r01":20,"r02":0,"r03":19,"r04":0,"r05":23,"r06":22,"r07":47,"r08":19,"r09":21,"r0a":21,"r0b":0,"r0c":0,"r0d":0,"r0e":22,"r0f":27,"r10":4,"r11":0,"r12":0,"r13":0,"r14":16,"r15":128,"r16":0,"r17":24,"r18":25,"r19":100,"r1a":0,"r1b":0,"r1c":0,"r1d":142,"r1e":70,"r1f":0,"r20":0,"r21":0,"r22":0,"r23":0,"r24":0,"r25":0,"r26":0,"r27":0,"r28":0,"r29":0,"r2a":0,"r2b":0,"r2c":0,"r2d":0,"r2e":0,"r2f":0,"r30":0,"r31":0,"r32":19,"r33":1,"r34":34,"r35":18,"r36":42,"r37":0,"r38":0,"r39":0,"r3a":21,"r3b":2,"r3c":2,"r3d":40,"r3e":10,"r3f":55,"r40":20,"r41":2,"r42":20,"r43":135,"r44":34,"r45":30,"r46":30,"r47":7,"r48":60,"r49":150,"r4a":10,"r4b":50,"r4c":20,"r4d":-8,"r4e":18,"r4f":60,"r50":20,"r51":0,"r52":20,"r53":10,"r54":50,"r55":0,"r56":0,"r57":3,"r58":0,"r59":0,"r5a":0,"r5b":0,"r5c":0,"r5d":0,"r5e":0,"r5f":0,"r60":0,"r61":64,"r62":69,"r63":1,"r64":3,"r65":3,"r66":0,"r67":0,"r68":764,"r69":514,"r6a":2,"r6b":-18944,"r6c":182,"r6d":-20480,"r6e":688,"r6f":2,"r70":0,"r71":2816,"r72":11,"r73":0,"r74":0,"r75":0,"r76":0,"r77":0,"r78":0,"r79":0,"r7a":0,"r7b":0,"r7c":0,"r7d":2,"r7e":2,"r7f":2,"time": "2021-11-19 17:05:48 CET","timestamp": 1637337948 }'
Traceback (most recent call last):
File "/config/custom_components/thermiq_mqtt/__init__.py", line 148, in message_received
hass.data[DOMAIN]._data['rf0']=hass.data[DOMAIN]._data['indr_t']
KeyError: 'indr_t'
```

+ Binary Sensors do not seem to work anymore...

**Comment by ThermIQ** [comment]
That is an error om my side, the new ThermIQ-room provides this value which is not existing in Thermiq-mqtt. 

Code is now updated to handle both

**Comment by barvidss** [comment]
I'm also having issues with the service "ThermIQ MQTT: write_reg" after updating to v1.0.0-rc3.

In Home Assistant - if I go to Developer tools -> Services -> ThermIQ MQTT: write_reg and run:
`service: thermiq_mqtt.write_reg
data:
  reg: 40
  value: 20
  bitmask: 2`

I get an "unknown error" and similar logs as karlvans (TypeError: a coroutine was expected, got None).

The strange thing is that the value is actually changed on the pump - but the errors causes my automations (where I call the write_reg service) to malfunction.
