### ISSUE TITLE
Services thermiq_mqtt.write_id and thermiq_mqtt.write_reg gives errors ( a coroutine was expected, got None)

### ISSUE THREAD

**Issue by barvidss** [ThermIQ/thermiq_mqtt-ha#6]
## Version of the custom_component

v1.0.0-rc3

## Configuration

```yaml

v1.0.0-rc3 of ThermIQ-MQTT with updated automations.yaml

```

## Describe the bug
When calling the services thermiq_mqtt.write_id and thermiq_mqtt.write_reg you get an "unknown error" and the Core log says "TypeError: a coroutine was expected, got None". I'm using the example data from the service:
`service: thermiq_mqtt.write_id
data:
  value_id: sensor.thermiq_rum_bor2
  value: 20
  bitmask: 2`

## Debug log

`2021-12-03 23:58:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547584302432] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 523, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1532, in _execute_service
    handler.job.target(service_call)
  File "/config/custom_components/thermiq_mqtt/__init__.py", line 221, in write_id_service
    hass.async_create_task(hass.components.mqtt.async_publish(conf.cmd_topic, msg,2,False))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None`

```

**Comment by ThermIQ** [comment]
I get that error as well but I can also see that the MQTT write message is sent properly. I will look into it for next release

**Comment by barvidss** [comment]
I installed the latest version of Thermiq-MQTT (v.1.1.2) and the error in the Core log looks different now. I still get the same error when trying to call thermiq_mqtt.write_reg (unknown error) and the register value isn't changed (and nothing shows up in MGTT Explorer).

`2021-12-12 22:08:30 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548144549840] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1259, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1532, in _execute_service
    handler.job.target(service_call)
  File "/config/custom_components/thermiq_mqtt/__init__.py", line 196, in write_reg_service
    hass.async_create_task(hass.components.mqtt.async_publish(conf.cmd_topic, msg))
TypeError: async_publish() missing 1 required positional argument: 'payload'`

**Comment by ThermIQ** [comment]
Closed with v1.2.0, Rrequires hass 21.12

**Comment by barvidss** [comment]
This is'nt solved.

I've upgraded to 1.2.2 and:

I can't change the value of "indoor target temp" from the lovelace card. The value returns to the previous value - no errors in the core log.

I can't call the "thermiq_mqtt.write_id" service. Gives me no errors in the UI but the core log says:
`2021-12-18 23:42:13 ERROR (MainThread) [custom_components.thermiq_mqtt] no value message sent due to faulty reg:[rum_bor2]`

Can't call the thermiq_mqtt.write_reg service. The UI gives me an unknown error and the core log says:
`2021-12-18 23:43:17 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'int' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1532, in _execute_service
    handler.job.target(service_call)
  File "/config/custom_components/thermiq_mqtt/__init__.py", line 372, in write_reg_service
    reg = reg.lower()
AttributeError: 'int' object has no attribute 'lower'
2021-12-18 23:43:17 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547612515392] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1532, in _execute_service
    handler.job.target(service_call)
  File "/config/custom_components/thermiq_mqtt/__init__.py", line 372, in write_reg_service
    reg = reg.lower()
AttributeError: 'int' object has no attribute 'lower'`
